version: '3'
services:
  api:
    image: openjdk:11.0.2-jdk-slim-stretch
    working_dir: /api
    command: ./mvnw spring-boot:run
    volumes:
      - ./api:/api
    networks:
      - overlay
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    networks:
      - overlay
    ports:
      - "27017:27017"

  ui:
    image: node:8-alpine
    working_dir: /ui
    command: npm run start
    volumes:
      - ./ui:/ui
    networks:
      - overlay
    ports:
        - "3000:3000"
    depends_on:
      - api

networks:
  overlay:
